# Generated by Django 3.2.7 on 2021-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('phoneNumber', models.CharField(max_length=15, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('education', models.CharField(max_length=20, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('knowlegde', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KodeeTrybee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Image1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('Image2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('Duration', models.CharField(max_length=50)),
                ('Fee', models.CharField(max_length=20)),
                ('Discount', models.CharField(max_length=20)),
                ('Content', models.TextField()),
                ('Level', models.CharField(max_length=20)),
                ('Push_date', models.DateField()),
                ('Url', models.CharField(max_length=50)),
            ],
        ),
    ]
