# Generated by Django 3.1.1 on 2021-08-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('Department', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('Academy_date', models.DateField()),
                ('Fee', models.CharField(max_length=50)),
                ('Discount', models.CharField(max_length=10)),
                ('Name2', models.CharField(max_length=20)),
                ('Image2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('Department2', models.CharField(max_length=50)),
                ('Duration2', models.CharField(max_length=50)),
                ('Academy_date2', models.DateField()),
                ('Fee2', models.CharField(max_length=50)),
                ('Discount2', models.CharField(max_length=10)),
            ],
        ),
    ]
